spring:
  banner:
    location: classpath:banner/documentsBanner.txt
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: DOCUMENT-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://educc0r:laia200619@sgiem-cluster.ghx2esb.mongodb.net/empsgiem

blob:
  connection-string: DefaultEndpointsProtocol=https;AccountName=sgiemstorage;AccountKey=iyO2i6qQ/m1gOZtQNU/9NQR+KEX1iKatyGbrbcxM3+uWssqsBl/l2WEXvX7hEyaXYKRb+V23kS4v+AStuWTw1g==;EndpointSuffix=core.windows.net
  container-name: sgiemcontainer

server:
  port: 8082